apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-maven
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-maven
  template:
    metadata:
      labels:
        app: myapp-maven
    spec:
      containers:
      - name: myapp-maven
        image: ebinvarghese/myapp-maven:2.0
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Service
metadata:
  name: test-app-service
spec:
  selector:
    app: myapp-maven
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort